### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by 0x0f0f0f** [xhsdf/rtile#1]
Here are some improvements.
-  Add a mode to increase or decrease the main window width (you call it "median") dinamically (while --all-auto mode is running)
- Add another mode to increase or decrease the other windows heights in --all-auto mode (--grow-_direction_ works but in -all-auto mode windows positions are reset immediately)
- Refresh window positions on minimize/maximize
- Add an option in the config to specify the max number of windows in the main panel and slave panel

**Comment by xhsdf** [comment]
I'll see what I can do about number 4 when I get home from work.  
I don't know how to get 'xprop -spy' to show maximizing/minimizing so I can't make any promises for number 3.  
2 doesn't seem feasible if I understand you correctly.  
1 looks like it will be a little more complicated, involving threads and sockets or pipes (which I have no experience with) so I don't know when I'll get around to that.

**Comment by 0x0f0f0f** [comment]
Points 1 & 2 could be easily implemented if you get somehow --all-auto mode to remember how windows are set with --grow.

Consider this in --all-auto mode

```
---------------------------------
|               |               |
|               |    terminal   |
|               |               |
|   firefox     |---------------|
|               |               |
|               |     gedit     |
|               |               |
---------------------------------
```

Right now if I --grow my main firefox window to the right it pushes and resizes the other two windows correctly and it gets like this

```
---------------------------------
|                  |            |
|                  | terminal   |
|                  |            |
|   firefox        |------------|
|                  |            |
|                  |  gedit     |
|                  |            |
---------------------------------
```

Now if I change window focus to the terminal all the windows reset to the original width.

So:
- The important thing is to get the --all-auto mode to coexist with --grow resized windows without resetting positions and sizes every refresh.
- You could add --grow-column-(left|right) and --grow-row-(up|down) to make all windows in a column or row to grow. This could replace point 1 and 2 from the previous comment I wrote.

However rtile deserves more popularity, it's waaay better than pyTyle

**Comment by xhsdf** [comment]
There are two problems with remembering window sizes:  
- it would completely change how the sizes are calculated. I tried something similar before and could not do it. I wanted to have size setting for window classes in the config but that never worked out  
- it would only work until you close or open a new window because then everything has to be recalculated anyway and if you don't open or close windows I would recommend not using -all-auto. That's what I do. I never used --all-auto once and only added it because someone requested it

I implemented point 4 and will add a setting to limit the number of columns probably later today. Not sure how to do point 1 yet, but it seems possible. I'm thinking about using named pipes. Or maybe a way to edit the config file directly.

> However rtile deserves more popularity, it's waaay better than pyTyle

Really glad you like it!
