### ISSUE TITLE
Multihead

### ISSUE THREAD

**Issue by gbdu** [xhsdf/rtile#3]
It would be nice to be able to select different column_configs for each monitor, or to be able to change them on the fly

**Comment by xhsdf** [comment]
Done.

**Comment by gbdu** [comment]
That was quick. Thank you. rtile.rb is a lifesaver

I was also working on another element called id for the column_config, so that if you call rtile.rb --all -c 1 it will use that, that way you can have multiple grid layouts and switch them on the fly, say with Mod-1 Mod-2 Mod-3. Now I don't know ruby at all so I'm just farting around and editing your code, I think I'm pretty close to a solution but the problem is that I'm keymapping Mod-A to tile --all in openbox and using it often, so I need to find a way to store the previously selected column_config

**Comment by xhsdf** [comment]
>That was quick

I got out of bed to make the change. If you had opened this ticket 10 minutes later I would have already been asleep.  
>Thank you. rtile.rb is a lifesaver

Glad to hear it!


I added a parameter to add entries to the config.  
Like this: rtile.rb --all '--add-to-config=<column_config windows="3" monitor="1" column_sizes="2, 1"/>'  
Since rtile always uses the last entry, you can use it to overwrite previous column_config elements.

Not the best solution for your problem but the cleanest I could think of. I hope it helps!

**Comment by gbdu** [comment]
I went ahead and had a crash course in ruby yesterday, added the ability to specify multiple layouts and the median https://github.com/xhsdf/rtile/commit/f7fc6c409aca0643877a92564258b01ad36c1910 as args

rtile is pretty efficient at what it does as a manual tiling script, but I have a lot of ideas I would like to implement (caching, persistent auto-tile, switching focus with mod + arrow keys, etc) which I think would make it diverge from your vision and probably make it bulky... anyway thanks for your help and this awesome script

**Comment by xhsdf** [comment]
>which I think would make it diverge from your vision

Yeah, I wish I never would have even implemented auto-tiling und now I can't just take it out again...

Not sure if that would fit your needs but have you thought about writing a wrapper instead of a fork?

**Comment by gbdu** [comment]
A wrapper would actually probably be a smarter idea... especially since I can use something other than Ruby. I'll definitely plan things out today and see
