### ISSUE TITLE
As of ruby 3.0.0 rexml is a gem ?

### ISSUE THREAD

**Issue by xstefen** [xhsdf/rtile#5]
Yep, im still using this beautiful script, thank you. As of updating my Arch system today, calling a rtile bind returned:

$ <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/bin/rtile:19:in `<main>'

I fixed it by performing `gem install rexml`

Not sure how that would be incorperated here so I didnt open a PR

Thank you

**Comment by xhsdf** [comment]
Glad to hear you are still using it!
And thank you for telling me about this. I actually didn't notice because the rexml gem got automatically installed when I installed another gem for a different script ruby 3.0.0 broke...
I don't think there is much I can do here. It's just the way it is now. I added it as a new dependency to the repo description.

**Comment by xstefen** [comment]
You're welcome. I wasnt sure you were even active anymore so I'm glad for the reply. I have learned that at least on archlinux there is a ruby-rexml package so that could satisfy the aur package at least. But more or less just bringing it to attention and leaving something for others to stumble upon in the future for a fix. Thanks again sir
